apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - statefulset.yaml

configMapGenerator:
  - name: ledger-postgres-init
    files:
      - 01-create-ledger-database.sh
